[package]
name = "textindex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
suffix = "1.2.0"
suffix_array = "0.5.0"
